# Constants for binary classification
MODIFYTRAJ = "MODIFY TRAJECTORY"
GENTARGETPOINT = "GENERATE TARGET POINT"

# Comprehensive training dataset - BINARY CLASSIFICATION ONLY
training_data = [
    # MODIFY TRAJECTORY examples - Path/Route modifications
    ("make the path wider", MODIFYTRAJ),
    ("narrow the trajectory", MODIFYTRAJ),
    ("keep distance from the wall", MODIFYTRAJ),
    ("avoid obstacles", MODIFYTRAJ),
    ("go around the left side", MODIFYTRAJ),
    ("take the right path", MODIFYTRAJ),
    ("make it smoother", MODIFYTRAJ),
    ("smooth out the trajectory", MODIFYTRAJ),
    ("reroute around this area", MODIFYTRAJ),
    ("hug the wall", MODIFYTRAJ),
    ("stay close to the edge", MODIFYTRAJ),
    ("give more clearance", MODIFYTRAJ),
    ("make the turns gentler", MODIFYTRAJ),
    ("reduce the curve radius", MODIFYTRAJ),
    ("straighten the path", MODIFYTRAJ),
    ("add more waypoints", MODIFYTRAJ),
    ("simplify the route", MODIFYTRAJ),
    ("optimize the path", MODIFYTRAJ),
    ("make it less jagged", MODIFYTRAJ),
    ("follow the contour", MODIFYTRAJ),
    ("adjust the trajectory angle", MODIFYTRAJ),
    ("change the approach direction", MODIFYTRAJ),
    ("modify the speed profile", MODIFYTRAJ),
    ("adjust the curvature", MODIFYTRAJ),
    ("shift the path to the left", MODIFYTRAJ),
    ("move the route away from here", MODIFYTRAJ),
    ("make a tighter turn", MODIFYTRAJ),
    ("widen the arc", MODIFYTRAJ),
    ("reduce oscillation", MODIFYTRAJ),
    ("dampen the motion", MODIFYTRAJ),
    ("increase path smoothness", MODIFYTRAJ),
    ("minimize jerky movements", MODIFYTRAJ),
    ("avoid sharp corners", MODIFYTRAJ),
    ("use gentle transitions", MODIFYTRAJ),
    ("follow the wall closely", MODIFYTRAJ),
    ("maintain safe distance", MODIFYTRAJ),
    ("keep away from obstacles", MODIFYTRAJ),
    ("navigate around the furniture", MODIFYTRAJ),
    ("take the scenic route", MODIFYTRAJ),
    ("use the most direct path", MODIFYTRAJ),
    ("slow down the approach", MODIFYTRAJ),
    ("speed up the trajectory", MODIFYTRAJ),
    ("make sharper turns", MODIFYTRAJ),
    ("soften the corners", MODIFYTRAJ),
    ("increase turning radius", MODIFYTRAJ),
    ("decrease path width", MODIFYTRAJ),
    ("expand the corridor", MODIFYTRAJ),
    ("compress the route", MODIFYTRAJ),
    ("elongate the path", MODIFYTRAJ),
    ("shorten the trajectory", MODIFYTRAJ),
    ("curve to the right", MODIFYTRAJ),
    ("bend to the left", MODIFYTRAJ),
    ("straighten this section", MODIFYTRAJ),
    ("add curvature here", MODIFYTRAJ),
    ("remove the zigzag", MODIFYTRAJ),
    ("create smoother transitions", MODIFYTRAJ),
    ("eliminate sudden direction changes", MODIFYTRAJ),
    ("reduce path complexity", MODIFYTRAJ),
    ("increase trajectory precision", MODIFYTRAJ),
    ("adjust the path shape", MODIFYTRAJ),
    ("modify route geometry", MODIFYTRAJ),
    ("change trajectory profile", MODIFYTRAJ),
    ("alter path dynamics", MODIFYTRAJ),
    ("update route characteristics", MODIFYTRAJ),
    ("revise trajectory behavior", MODIFYTRAJ),
    ("reshape the path", MODIFYTRAJ),
    ("reconfigure the route", MODIFYTRAJ),
    ("redesign trajectory flow", MODIFYTRAJ),
    ("restructure path layout", MODIFYTRAJ),
    ("redefine route parameters", MODIFYTRAJ),
    ("tune trajectory settings", MODIFYTRAJ),
    ("calibrate path response", MODIFYTRAJ),
    ("fine-tune route behavior", MODIFYTRAJ),
    ("optimize trajectory performance", MODIFYTRAJ),
    ("enhance path efficiency", MODIFYTRAJ),
    ("improve route smoothness", MODIFYTRAJ),
    ("refine trajectory quality", MODIFYTRAJ),
    ("perfect path execution", MODIFYTRAJ),
    ("polish route delivery", MODIFYTRAJ),
    ("make the path less aggressive", MODIFYTRAJ),
    ("reduce the steering angle", MODIFYTRAJ),
    ("increase the safety margin", MODIFYTRAJ),
    ("decrease the velocity profile", MODIFYTRAJ),
    ("smooth the acceleration", MODIFYTRAJ),
    ("reduce the jerk", MODIFYTRAJ),
    ("minimize the turning force", MODIFYTRAJ),
    ("optimize for comfort", MODIFYTRAJ),
    ("prioritize stability", MODIFYTRAJ),
    ("emphasize smoothness", MODIFYTRAJ),
    ("focus on efficiency", MODIFYTRAJ),
    ("balance speed and safety", MODIFYTRAJ),
    ("adjust for obstacles", MODIFYTRAJ),
    ("compensate for drift", MODIFYTRAJ),
    ("correct the alignment", MODIFYTRAJ),
    ("fix the trajectory error", MODIFYTRAJ),
    ("repair the path deviation", MODIFYTRAJ),
    ("resolve the route issue", MODIFYTRAJ),
    ("address the navigation problem", MODIFYTRAJ),
    ("handle the path conflict", MODIFYTRAJ),
    ("deal with the routing error", MODIFYTRAJ),
    ("manage the trajectory fault", MODIFYTRAJ),
    ("process the path correction", MODIFYTRAJ),
    ("execute the route fix", MODIFYTRAJ),
    ("implement the trajectory update", MODIFYTRAJ),
    ("apply the path modification", MODIFYTRAJ),
    ("perform the route adjustment", MODIFYTRAJ),
    ("conduct the trajectory revision", MODIFYTRAJ),
    ("carry out the path refinement", MODIFYTRAJ),
    ("accomplish the route enhancement", MODIFYTRAJ),
    
    # GENERATE TARGET POINT examples - Destination/Goal setting
    ("go to the kitchen", GENTARGETPOINT),
    ("set target at the door", GENTARGETPOINT),
    ("place a waypoint here", GENTARGETPOINT),
    ("target the corner", GENTARGETPOINT),
    ("head to coordinates 5,3", GENTARGETPOINT),
    ("destination is the charging station", GENTARGETPOINT),
    ("endpoint should be near the table", GENTARGETPOINT),
    ("goal is in front of me", GENTARGETPOINT),
    ("navigate to the window", GENTARGETPOINT),
    ("set the goal near the bookshelf", GENTARGETPOINT),
    ("target location is by the couch", GENTARGETPOINT),
    ("go to position x=10, y=20", GENTARGETPOINT),
    ("head towards the exit", GENTARGETPOINT),
    ("move to the center of the room", GENTARGETPOINT),
    ("destination is the far corner", GENTARGETPOINT),
    ("set waypoint at the intersection", GENTARGETPOINT),
    ("target the pickup location", GENTARGETPOINT),
    ("go to the delivery point", GENTARGETPOINT),
    ("navigate to home base", GENTARGETPOINT),
    ("set goal at the marker", GENTARGETPOINT),
    ("target behind the chair", GENTARGETPOINT),
    ("go to the balcony", GENTARGETPOINT),
    ("head to the garage", GENTARGETPOINT),
    ("destination is the parking spot", GENTARGETPOINT),
    ("move to the loading dock", GENTARGETPOINT),
    ("target the assembly line", GENTARGETPOINT),
    ("go to station 3", GENTARGETPOINT),
    ("set endpoint at the workbench", GENTARGETPOINT),
    ("navigate to the supply closet", GENTARGETPOINT),
    ("target the storage area", GENTARGETPOINT),
    ("go to the meeting point", GENTARGETPOINT),
    ("head to checkpoint Alpha", GENTARGETPOINT),
    ("destination is the service bay", GENTARGETPOINT),
    ("move to the inspection zone", GENTARGETPOINT),
    ("target the cleaning station", GENTARGETPOINT),
    ("go to the rest area", GENTARGETPOINT),
    ("set goal at the reception desk", GENTARGETPOINT),
    ("navigate to the elevator", GENTARGETPOINT),
    ("target the stairwell", GENTARGETPOINT),
    ("go to the emergency exit", GENTARGETPOINT),
    ("move to the north wall", GENTARGETPOINT),
    ("target the south entrance", GENTARGETPOINT),
    ("go to the east corridor", GENTARGETPOINT),
    ("head to the west wing", GENTARGETPOINT),
    ("destination is upstairs", GENTARGETPOINT),
    ("target downstairs", GENTARGETPOINT),
    ("go to the basement", GENTARGETPOINT),
    ("move to the rooftop", GENTARGETPOINT),
    ("target the first floor", GENTARGETPOINT),
    ("head to the second level", GENTARGETPOINT),
    ("go to room 101", GENTARGETPOINT),
    ("target suite 205", GENTARGETPOINT),
    ("move to office A", GENTARGETPOINT),
    ("head to conference room B", GENTARGETPOINT),
    ("go to lab 3", GENTARGETPOINT),
    ("target workshop 7", GENTARGETPOINT),
    ("move to storage unit 12", GENTARGETPOINT),
    ("head to platform 9", GENTARGETPOINT),
    ("go to dock 4", GENTARGETPOINT),
    ("target bay 6", GENTARGETPOINT),
    ("move to sector 8", GENTARGETPOINT),
    ("head to zone 2", GENTARGETPOINT),
    ("go to area 5", GENTARGETPOINT),
    ("target region 1", GENTARGETPOINT),
    ("move to quadrant 3", GENTARGETPOINT),
    ("head to grid A7", GENTARGETPOINT),
    ("go to coordinates (15,25)", GENTARGETPOINT),
    ("target position 40,60", GENTARGETPOINT),
    ("move to location [20,30]", GENTARGETPOINT),
    ("head to point (0,0)", GENTARGETPOINT),
    ("go to origin", GENTARGETPOINT),
    ("target the center", GENTARGETPOINT),
    ("move to the middle", GENTARGETPOINT),
    ("head to the focal point", GENTARGETPOINT),
    ("go to the junction", GENTARGETPOINT),
    ("target the crossroads", GENTARGETPOINT),
    ("move to the hub", GENTARGETPOINT),
    ("head to the nexus", GENTARGETPOINT),
    ("position the robot at the door", GENTARGETPOINT),
    ("position the robot near me", GENTARGETPOINT),
    ("place the robot in front of the table", GENTARGETPOINT),
    ("place the robot behind the chair", GENTARGETPOINT),
    ("put the robot at coordinates 10,5", GENTARGETPOINT),
    ("put the robot in the corner", GENTARGETPOINT),
    ("move the robot to the left", GENTARGETPOINT),
    ("move the robot to the right", GENTARGETPOINT),
    ("move the robot forward", GENTARGETPOINT),
    ("move the robot backward", GENTARGETPOINT),
    ("take the robot to the kitchen", GENTARGETPOINT),
    ("take the robot to the garage", GENTARGETPOINT),
    ("get the robot to the charging station", GENTARGETPOINT),
    ("get the robot to position A", GENTARGETPOINT),
    ("robot should go to the window", GENTARGETPOINT),
    ("robot should move to the door", GENTARGETPOINT),
    ("robot needs to be at the table", GENTARGETPOINT),
    ("robot needs to go to station 5", GENTARGETPOINT),
    ("send the robot to the warehouse", GENTARGETPOINT),
    ("dispatch to location B", GENTARGETPOINT),
    ("deploy at coordinates 25,40", GENTARGETPOINT),
    ("station the robot near the entrance", GENTARGETPOINT),
    ("locate the robot at the checkpoint", GENTARGETPOINT),
    ("situate at the designated spot", GENTARGETPOINT),
    ("establish position at the terminal", GENTARGETPOINT),
    ("install at the monitoring post", GENTARGETPOINT),
    ("arrange at the pickup zone", GENTARGETPOINT),
    ("organize at the sorting area", GENTARGETPOINT),
    ("configure at the staging point", GENTARGETPOINT),
    ("set up at the distribution center", GENTARGETPOINT),
    ("prepare at the processing station", GENTARGETPOINT),
    ("ready at the control room", GENTARGETPOINT),
    ("initialize at the start position", GENTARGETPOINT),
    ("activate at the launch pad", GENTARGETPOINT),
    ("engage at the mission point", GENTARGETPOINT),
    ("commence at the operation base", GENTARGETPOINT),
    ("begin at the task location", GENTARGETPOINT),
    ("start at the assignment area", GENTARGETPOINT),
    ("proceed to the destination", GENTARGETPOINT),
    ("advance to the target zone", GENTARGETPOINT),
    ("progress to the objective point", GENTARGETPOINT),
    ("continue to the endpoint", GENTARGETPOINT),
    ("travel to the final location", GENTARGETPOINT),
    ("journey to the specified coordinates", GENTARGETPOINT),
    ("voyage to the marked position", GENTARGETPOINT),
    ("migrate to the new station", GENTARGETPOINT),
    ("relocate to the alternate site", GENTARGETPOINT),
    ("transfer to the backup location", GENTARGETPOINT),
    ("shift to the secondary position", GENTARGETPOINT),
    ("transition to the next waypoint", GENTARGETPOINT),
    ("convert to the updated coordinates", GENTARGETPOINT),
    ("transform to the revised location", GENTARGETPOINT),
    ("change to the modified position", GENTARGETPOINT),
    ("switch to the adjusted coordinates", GENTARGETPOINT),
    ("alter to the corrected location", GENTARGETPOINT),
]

# Edge cases and boundary examples for better classification
edge_cases = [
    # Clear trajectory modifications (no new destinations)
    ("find a better route to get there", MODIFYTRAJ),  # assumes existing target
    ("adjust course to target", MODIFYTRAJ),  # assumes existing target
    ("approach from the other side", MODIFYTRAJ),
    ("change direction", MODIFYTRAJ),
    ("alter the approach", MODIFYTRAJ),
    ("modify the route", MODIFYTRAJ),
    ("update the path", MODIFYTRAJ),
    ("revise the trajectory", MODIFYTRAJ),
    ("improve the route", MODIFYTRAJ),
    ("enhance the path", MODIFYTRAJ),
    ("I don't like the trajectory make it smoother", MODIFYTRAJ),
    ("the path is wrong make it wider", MODIFYTRAJ),
    ("this route is bad straighten it out", MODIFYTRAJ),
    ("trajectory looks weird smooth the curves", MODIFYTRAJ),
    ("path doesn't work avoid the obstacles", MODIFYTRAJ),
    ("current route is bad take the left side", MODIFYTRAJ),
    ("trajectory ends too sharp soften the approach", MODIFYTRAJ),
    ("path stops too abruptly slow down the ending", MODIFYTRAJ),
    ("route finishes badly smooth the final approach", MODIFYTRAJ),
    ("trajectory terminates roughly gentle the conclusion", MODIFYTRAJ),
    ("path conclusion is sharp reduce the final curvature", MODIFYTRAJ),
    ("route ending is rough smooth out the terminus", MODIFYTRAJ),
    ("trajectory finish is abrupt ease the final segment", MODIFYTRAJ),
    ("path completion rough soften the ending", MODIFYTRAJ),
    ("route destination approach bad smooth the arrival", MODIFYTRAJ),
    ("the robot is going the wrong way", MODIFYTRAJ),
    ("turn around and go back", MODIFYTRAJ),
    ("reverse the direction", MODIFYTRAJ),
    ("flip the trajectory", MODIFYTRAJ),
    ("invert the path", MODIFYTRAJ),
    ("mirror the route", MODIFYTRAJ),
    ("backtrack along the path", MODIFYTRAJ),
    ("retrace the trajectory", MODIFYTRAJ),
    ("undo the last movement", MODIFYTRAJ),
    ("correct the navigation error", MODIFYTRAJ),
    
    # Clear destination changes
    ("redirect to new location", GENTARGETPOINT),
    ("plan path to new waypoint", GENTARGETPOINT),
    ("target somewhere safer", GENTARGETPOINT),
    ("go somewhere else", GENTARGETPOINT),
    ("move to a different spot", GENTARGETPOINT),
    ("head to another place", GENTARGETPOINT),
    ("target a new destination", GENTARGETPOINT),
    ("set a different goal", GENTARGETPOINT),
    ("choose new endpoint", GENTARGETPOINT),
    ("select different waypoint", GENTARGETPOINT),
    ("change destination to the lobby", GENTARGETPOINT),
    ("new target is the cafeteria", GENTARGETPOINT),
    ("update goal to the library", GENTARGETPOINT),
    ("revise destination to building C", GENTARGETPOINT),
    ("modify target to floor 5", GENTARGETPOINT),
    ("adjust endpoint to the parking lot", GENTARGETPOINT),
    ("switch destination to the auditorium", GENTARGETPOINT),
    ("alter goal to the gymnasium", GENTARGETPOINT),
    ("convert target to the laboratory", GENTARGETPOINT),
    ("transform destination to the workshop", GENTARGETPOINT),
    ("relocate goal to the courtyard", GENTARGETPOINT),
    ("migrate target to the playground", GENTARGETPOINT),
    ("transfer destination to the clinic", GENTARGETPOINT),
    ("shift goal to the pharmacy", GENTARGETPOINT),
    ("redirect target to the bakery", GENTARGETPOINT),
    ("reroute to the market", GENTARGETPOINT),
    ("reposition to the bank", GENTARGETPOINT),
    ("reassign to the post office", GENTARGETPOINT),
    ("reallocate to the fire station", GENTARGETPOINT),
    ("redistribute to the police station", GENTARGETPOINT),
    ("cancel current target go to home", GENTARGETPOINT),
    ("abort mission head to base", GENTARGETPOINT),
    ("stop current task go to maintenance", GENTARGETPOINT),
    ("halt operation move to safe zone", GENTARGETPOINT),
    ("terminate sequence return to dock", GENTARGETPOINT),
    ("end current path go to shelter", GENTARGETPOINT),
    ("quit route head to parking", GENTARGETPOINT),
    ("cease navigation go to standby", GENTARGETPOINT),
    ("discontinue path move to idle position", GENTARGETPOINT),
    ("suspend route go to waiting area", GENTARGETPOINT),
]

# Additional contextual examples for robustness
contextual_examples = [
    # Speed and timing modifications (trajectory)
    ("slow down when turning", MODIFYTRAJ),
    ("speed up on straight sections", MODIFYTRAJ),
    ("maintain constant velocity", MODIFYTRAJ),
    ("accelerate gradually", MODIFYTRAJ),
    ("decelerate smoothly", MODIFYTRAJ),
    ("pause at the intersection", MODIFYTRAJ),
    ("stop before the obstacle", MODIFYTRAJ),
    ("wait at the crossing", MODIFYTRAJ),
    ("hold position briefly", MODIFYTRAJ),
    ("resume movement after delay", MODIFYTRAJ),
    
    # Orientation and heading adjustments (trajectory)
    ("face the wall", MODIFYTRAJ),
    ("turn to face the door", MODIFYTRAJ),
    ("orient towards the window", MODIFYTRAJ),
    ("align with the corridor", MODIFYTRAJ),
    ("rotate 90 degrees", MODIFYTRAJ),
    ("spin around", MODIFYTRAJ),
    ("pivot to the left", MODIFYTRAJ),
    ("swivel to the right", MODIFYTRAJ),
    ("adjust heading", MODIFYTRAJ),
    ("correct orientation", MODIFYTRAJ),
    
    # Formation and pattern following (trajectory)
    ("follow the leader", MODIFYTRAJ),
    ("maintain formation", MODIFYTRAJ),
    ("stay in line", MODIFYTRAJ),
    ("keep proper spacing", MODIFYTRAJ),
    ("match the pattern", MODIFYTRAJ),
    ("synchronize movement", MODIFYTRAJ),
    ("coordinate with team", MODIFYTRAJ),
    ("align with group", MODIFYTRAJ),
    ("follow the convoy", MODIFYTRAJ),
    ("maintain the queue", MODIFYTRAJ),
    
    # Environmental responses (trajectory)
    ("adapt to weather conditions", MODIFYTRAJ),
    ("adjust for lighting changes", MODIFYTRAJ),
    ("compensate for wind", MODIFYTRAJ),
    ("account for traffic", MODIFYTRAJ),
    ("respond to crowd density", MODIFYTRAJ),
    ("accommodate pedestrians", MODIFYTRAJ),
    ("yield to other robots", MODIFYTRAJ),
    ("defer to priority vehicles", MODIFYTRAJ),
    ("respect right of way", MODIFYTRAJ),
    ("follow traffic rules", MODIFYTRAJ),
    
    # Specific location targeting (target point)
    ("meet me at the fountain", GENTARGETPOINT),
    ("rendezvous at the plaza", GENTARGETPOINT),
    ("converge on the monument", GENTARGETPOINT),
    ("gather at the pavilion", GENTARGETPOINT),
    ("assemble at the amphitheater", GENTARGETPOINT),
    ("convene at the conference center", GENTARGETPOINT),
    ("congregate at the town square", GENTARGETPOINT),
    ("unite at the memorial", GENTARGETPOINT),
    ("join at the sculpture garden", GENTARGETPOINT),
    ("connect at the observation deck", GENTARGETPOINT),
    
    # Emergency and priority destinations (target point)
    ("emergency evacuation to exit A", GENTARGETPOINT),
    ("urgent delivery to room 502", GENTARGETPOINT),
    ("priority transport to ICU", GENTARGETPOINT),
    ("immediate response to alarm location", GENTARGETPOINT),
    ("critical mission to reactor room", GENTARGETPOINT),
    ("emergency backup to generator room", GENTARGETPOINT),
    ("urgent maintenance to server room", GENTARGETPOINT),
    ("priority rescue to stairwell B", GENTARGETPOINT),
    ("immediate assistance to medical bay", GENTARGETPOINT),
    ("critical support to command center", GENTARGETPOINT),
    
    # Relative positioning (target point)
    ("position 5 meters from the wall", GENTARGETPOINT),
    ("stay 2 feet away from the edge", GENTARGETPOINT),
    ("maintain 1 meter clearance", GENTARGETPOINT),
    ("keep 3 units distance", GENTARGETPOINT),
    ("establish 4 foot buffer", GENTARGETPOINT),
    ("create 6 inch gap", GENTARGETPOINT),
    ("preserve 10 centimeter space", GENTARGETPOINT),
    ("hold 2 yard separation", GENTARGETPOINT),
    ("sustain 5 meter interval", GENTARGETPOINT),
    ("retain 8 foot margin", GENTARGETPOINT),
]